### ISSUE TITLE
Data of `label_class_dict.csv`

### ISSUE THREAD

**Issue by ShaoshuSu** [shaswata09/Offroad-Path-Planning#1]
Hi there,

Thanks for your interesting work! 

I encountered a small issue when I attempted to run your Colab notebook, I noticed that the `label_class_dict.csv` file was missing. Could you please direct me to where I might find these files?

Thanks!

**Comment by ShaoshuSu** [comment]
Sorry, just found [here](https://www.kaggle.com/datasets/mitrashaswata/msstate-cavs-off-road-aerial-images?resource=download).
Thank you!

**Comment by ShaoshuSu** [comment]
One follow-up question, do you provide the pretrain weights of `best_model_unet_softmax_cavs.pth` and `best_model_deeplab_softmax_cavs.pth` maybe? Thanks!

**Comment by shaswata09** [comment]
Hei,

Thanks for reaching out. No, the trained models have not been uploaded to the repo. I'll see how I can upload it. 

Best,
Shaswata
